/* 
  action Types
*/
export const UPDATE_PRODUCT_BASIC_DETAILS = "UPDATE_PRODUCT_BASIC_DETAILS";
export const UPDATE_PRODUCT_QTY_DETAILS = "UPDATE_PRODUCT_QTY_DETAILS";
export const ADD_QTY_PRICE_BREAK = "ADD_QTY_PRICE_BREAK";
export const REMOVE_QTY_PRICE_BREAK = "REMOVE_QTY_PRICE_BREAK";
export const UPDATE_QTY_PRICE_BREAK = "UPDATE_QTY_PRICE_BREAK";
export const RESET_PRODUCT_QTY_SETTINGS = "RESET_PRODUCT_QTY_SETTINGS";
export const RESET_QTY_PRICE_BREAK = "RESET_QTY_PRICE_BREAK";
export const TOGGLE_PRICEBREAK_VIEW = "TOGGLE_PRICEBREAK_VIEW";
export const TOGGLE_ARRIVALDATE_VIEW = "TOGGLE_ARRIVALDATE_VIEW";
export const TOGGLE_MAXPURCHASEQTY_VIEW = "TOGGLE_MAXPURCHASEQTY_VIEW";
export const SET_SELECTED_PRODUCT_ID = "SET_SELECTED_PRODUCT_ID";
export const GET_PRODUCTS_COUNT = "GET_PRODCUTS_COUNT";

export const UPDATE_VERB = "UPDATE_VERB";
export const UPDATE_PATH = "UPDATE_PATH";
export const UPDATE_PARAMS = "UPDATE_PARAMS";
export const SEND_REQUEST = "SEND_REQUEST";
export const REQUEST_START = "REQUEST_START";
export const REQUEST_COMPLETE = "REQUEST_COMPLETE";
export const REQUEST_ERROR = "REQUEST_ERROR";
